### PR TITLE
Remove ANY option for interpolated property quality

### LINKED ISSUE #326: Get interpolated property values quality "ANY"
**What happened**:
Updated the "Quality" setting of Get interpolated property values to "GOOD" then "ANY" and saw an error:
image

**What you expected to happen**:
Data is successfully fetched for any quality.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a query for "Get interpolated property values"
2. Choose an asset and asset property (DOUBLE value type)
3. Change the "Quality" setting to "GOOD"
4. Change the "Quality" setting to "ANY"
5. See the error

**Screenshots**

https://github.com/grafana/iot-sitewise-datasource/assets/87385528/b1de01a8-e37e-4fa1-b58d-d647359fbc39

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.0
- Plugin version: 1.12.1
- OS Grafana is installed on: MacOS
- User OS & Browser: Sonoma 14.5, Chrome
- Others: Amazon Managed Grafana environment

### PR DESCRIPTION
**Pull request by iwysiu**
**What this PR does / why we need it**:
When a "Get interpolated property values" query is used with `Quality` set to `ANY` (which is the default option) it errors because it's not a [valid value for the query](https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_GetInterpolatedAssetPropertyValues.html#API_GetInterpolatedAssetPropertyValues_RequestSyntax). This PR removes it from the options for interpolated queries and automatically replaces `ANY` with `GOOD` on the backend (since it works on a first run and by using `GOOD` that's probably in line with users expect)

**Which issue(s) this PR fixes**:

Fixes #326

**Special notes for your reviewer**:

### CODE REVIEW

File: src/components/query/QualityAndOrderRow.tsx [hunk 1]
```diff
@@ -104,14 +104,18 @@ export class QualityAndOrderRow extends PureComponent<Props> {
 
   render() {
     const { query } = this.props;
+    let currQualities = qualities;
+    if (query.queryType === QueryType.PropertyInterpolated) {
+      currQualities = qualities.slice(1);
+    }
```
Comment (kevinwcyu) [inline src/components/query/QualityAndOrderRow.tsx:110]: nit:

add this to the top of the file underneath where `const qualities` is defined so it's only created once.

```
const interpolatedPropertyQualities: Array<SelectableValue<SiteWiseQuality>> = qualities.slice(1);
```

and change this here to

```suggestion
    const currQualities = query.queryType === QueryType.PropertyInterpolated ? interpolatedPropertyQualities : qualities;
```

**Review by kevinwcyu — APPROVED** [review]

File: src/components/query/QualityAndOrderRow.tsx (hunk 1 above)
Comment (iwysiu) [reply src/components/query/QualityAndOrderRow.tsx]: done
